# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
#  Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    X-Frame-Options = "DENY"
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"

